export const REQUEST_EVENTS = 'REQUEST_EVENTS';
export const RECEIVE_EVENTS = 'RECEIVE_EVENTS';
export const RECEIVE_EVENTS_ERROR = 'RECEIVE_EVENTS_ERROR';
export const SELECT_DAY = 'SELECT_DAY';
export const INVALIDATE_DAY = 'INVALIDATE_DAY';
